# `Exercise `
<a id='Exercise '></a>

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.


# `Exercise A`
<a id='Exercise A'></a>


In [19]:
import numpy as np  # Import the NumPy library for numerical operations

# Create a nested Python list with values from 1 to 9
data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

A = np.array(data)  # Convert the nested list into a NumPy ndarray

print(A)  # Display the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]



# `Explanation`
<a id='Explanation'></a>

import numpy as np → Imports NumPy and assigns alias np
list_data = [...] → Creates a nested list (2D structure)
np.array(list_data) → Converts the list into an ndarray
print(A) → Displays the array

# Using `ndarray property, method of the ndarray object, using numpy function and passing an ndarray`

In [20]:
import numpy as np  # Import NumPy library

data = [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

A = np.array(data)  # Convert list to ndarray

print("Shape:", A.shape)  # Get the dimensions of the array

print("max:", A.max())  # Get the maximum value in the array

print("max(A):",np.max(A))  # Get the maximum value using NumPy

Shape: (3, 3)
max: 90
max(A): 90


# `Explanation `
<a id='Explanation '></a>

- A nested list was created and converted into a NumPy ndarray.
- A.shape was used to check the dimensions of the array.
- A.max() returns the highest value using an ndarray method.
- np.max(A) returns the same result using a NumPy function.

# `Exercise B`
<a id='Exercise B'></a>


In [21]:
import numpy as np  # Import NumPy library

B = np.ones((5, 5), dtype=int)  # Create a 5x5 array filled with 1s (integer type)

print(B)  # Display the array

print("Shape:", B.shape)  # Check the shape of the array
print("Size:", B.size)   # Check the total number of elements
print("NDim:", B.ndim)   # Check the number of dimensions

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Shape: (5, 5)
Size: 25
NDim: 2


# `Explanation`
<a id='Explanation'></a>

- np.ones() was used to create a 5x5 array filled with ones.
- B.shape shows the dimensions (5x5).
- B.size shows the total number of elements (25).
- B.ndim shows that the array is 2-dimensional.

# `Exercise C`
<a id='Exercise C'></a>

In [22]:
import numpy as np  # Import NumPy library

C = np.arange(-5, 6)  # Create an array from -5 to +5

result = C * 2  # Multiply each element by 2

print(result)  # Display the resulting array

[-10  -8  -6  -4  -2   0   2   4   6   8  10]


# `Explanation`
<a id='Explanation'></a>

- np.arange(-5, 6) generates values from -5 to 5.
- Each value was multiplied by 2 using element-wise operation.
- The result shows the transformed array.